 # NUMPY
 
 
 ---> Numerical Python  

import numpy as np


<b> creating a new numpy array </b> 

In [3]:
var=np.array([1,4,9,16,25,36])     
print(var)

[ 1  4  9 16 25 36]


In [4]:
print(type(var))

<class 'numpy.ndarray'>


In [5]:
print(var.shape)

(6,)


In [7]:
print(var.dtype)

int32


<b> Indexing </b>

In [6]:
print(var[0]+var[-1])

37


In [9]:
var2=np.array([[1,2,3,4,5],[1,4,9,16,25]])
print(var2)
print(var2.ndim)
print(var2.shape)
print(var2.dtype)

[[ 1  2  3  4  5]
 [ 1  4  9 16 25]]
2
(2, 5)
int32


In [10]:
print(var2[0,1])

2


In [11]:
print(var2[1,2])

9


<b> slicing </b>

In [13]:
print(var[1:])

[ 4  9 16 25 36]


In [15]:
print(var[ :4])

[ 1  4  9 16]


In [21]:
print(var2[0, 1:4 ])

[2 3 4]


In [20]:
print(var2[1, 1:4 ])

[ 4  9 16]


<b> copy vs view </b> 


copy creates a own copy.



view is the just original data.

In [24]:
var3=np.array(["JNTU", "OU", "CBIT", "VASAVI", "VNR VJIET"])

my_copy=var3.copy()
my_view=var3.view()


(var3[3], var3[4]) = (var3[4], var3[3])

print(my_copy)
print("")
print(my_view)

['JNTU' 'OU' 'CBIT' 'VASAVI' 'VNR VJIET']

['JNTU' 'OU' 'CBIT' 'VNR VJIET' 'VASAVI']


<b> Reshaping </b>

In [26]:
org = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

new=org.reshape(4,4)

print(new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
new2=org.reshape(3,6)
print(new2)

ValueError: cannot reshape array of size 16 into shape (3,6)

<b> joining numpy arrays </b>

In [30]:
a=np.array([1,2,3,4,5])
b=np.array(["one","two","three","four","five"])
c=np.concatenate((a,b))
print(c)

['1' '2' '3' '4' '5' 'one' 'two' 'three' 'four' 'five']


In [2]:
import numpy as np
first=np.array([[1,2],[3,4]])
second = np.array([[10,20],[30,40]])

join=np.concatenate((first,second), axis =1)
print(join)

[[ 1  2 10 20]
 [ 3  4 30 40]]
