# Numpy -2


<b> Splitting the array
    

1-d

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3) # this method helps to split

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


<b> 2-d </b>

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [35]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)
print("")
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]



<b> Random Number </b>


not just diff.num at each time, but an unpredicted number logically.


<b> Generate a random number </b> 

In [39]:
from numpy import random
die_roll=random.randint(1,7)

print(die_roll)

1


<b> Generate of random array </b>

for 1-d

In [7]:
x=random.randint(100, size=(6))

print(x)

[25  3 45 89 52 42]


For 2-d

In [8]:
x = random.randint(10, size=(4, 4))

print(x)

[[4 9 4 4]
 [1 8 8 4]
 [9 0 0 4]
 [1 3 7 2]]


<b> Random Permutation </b>

An arrangement of the elements. 


2 Methods are there.

In [41]:
from numpy import random
import numpy as np

arr = np.array([11, 12, 13, 14, 15])

random.shuffle(arr) # original arrray will be modified

print(arr)


[15 13 11 12 14]


In [34]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))
print("")
print(arr)                       # won't effect original array


[3 5 1 4 2]

[1 2 3 4 5]
